export default [
  {
    name: "leather2",
    textures: {
      albedo: null,
      ao: null,
      dx: null,
      height: null,
      metallic: null,
      roughness: null,
    },
    preview: "/images/leather2.jpg",
    alt: "초기소재",
  },
  {
    name: "asphalt",
    textures: {
      albedo: "/images/asphalt/albedo.png",
      ao: "/images/asphalt/ao.png",
      dx: "/images/asphalt/dx.png",
      height: "/images/asphalt/Height.png",
      metallic: "/images/asphalt/Metallic.png",
      roughness: "/images/asphalt/Roughness.png",
    },
    preview: "/images/asphalt/preview.jpg",
    alt: "아스팔트",
  },
  {
    name: "beastFur",
    textures: {
      albedo: "/images/beast-fur/stylized-beast-fur_albedo.png",
      ao: "/images/beast-fur/stylized-beast-fur_ao.png",
      dx: "/images/beast-fur/stylized-beast-fur_normal-dx.png",
      height: "/images/beast-fur/stylized-beast-fur_height.png",
      metallic: "/images/beast-fur/stylized-beast-fur_metallic.png",
      roughness: "/images/beast-fur/stylized-beast-fur_roughness.png",
    },
    preview: "/images/beast-fur/stylized-beast-fur_preview.jpg",
    alt: "모피",
  },
  {
    name: "weaving",
    textures: {
      albedo: "/images/dirty-wicker/dirty-wicker-albedo.png",
      ao: "/images/dirty-wicker/dirty-wicker-ao.png",
      dx: "/images/dirty-wicker/dirty-wicker-dx.png",
      height: "/images/dirty-wicker/dirty-wicker-height.png",
      metallic: "/images/dirty-wicker/dirty-wicker-metallic.png",
      roughness: "/images/dirty-wicker/dirty-wicker-roughness.png",
    },
    preview: "/images/dirty-wicker/dirty-wicker-preview.jpg",
    alt: "위빙",
  },

  {
    name: "basket",
    textures: {
      albedo: "/images/basket-weave/simple-basket-weave1-albedo.png",
      ao: "/images/basket-weave/simple-basket-weave1-ao.png",
      dx: "/images/basket-weave/simple-basket-weave1-dx.png",
      height: "/images/basket-weave/simple-basket-weave1-height.png",
      metallic: "/images/basket-weave/simple-basket-weave1-metallic.png",
      roughness: "/images/basket-weave/simple-basket-weave1-roughness.png",
    },
    preview: "/images/basket-weave/simple-basket-weave1-preview.jpg",
    alt: "대나무",
  },
  {
    name: "suedo",
    textures: {
      albedo: "/images/old-fabric/coarse-old-fabric_albedo.png",
      ao: "/images/old-fabric/coarse-old-fabric_ao.png",
      dx: "/images/old-fabric/coarse-old-fabric_dx.png",
      height: "/images/old-fabric/coarse-old-fabric_height.png",
      metallic: "/images/old-fabric/coarse-old-fabric_metallic.png",
      roughness: "/images/old-fabric/coarse-old-fabric_roughness.png",
    },
    preview: "/images/old-fabric/coarse-old-fabric_preview.jpg",
    alt: "스웨이드",
  },
];
